# Generated by Django 2.1 on 2018-08-10 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_taskmodel_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskmodel',
            name='description',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
    ]
