# Generated by Django 2.1 on 2018-08-12 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_auto_20180810_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskmodel',
            name='parent_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='todo.TaskModel'),
        ),
    ]
